### ISSUE TITLE
way to erase the unwanted namespace?

### ISSUE THREAD

**Issue by fommil** [djspiewak/shims#13]
First, this is amazing, thank you so much!

My first usecase for shims didn't go so well. My work project uses cats and we often find ourselves wanting to use scalaz to get extra features or workaround bugs in cats (usually lazy evaluation bugs). I wanted to be able to use shims to write one function in scalaz and then convert it to our "public api" (cats). However, since the file already had the `import cats._` stuff, I was getting this sort of thing

```
type mismatch;
[error]  found   : F[Option[A]]
[error]  required: ?{def map: ?}
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method toFunctorOps in trait ToFunctorOps of type [F[_], A](target: F[A])(implicit tc: cats.Functor[F])cats.Functor.Ops[F,A]{type TypeClassType = cats.Functor[F]}
[error]  and method ToFunctorOps in trait ToFunctorOps of type [F[_], A](v: F[A])(implicit F0: scalaz.Functor[F])scalaz.syntax.FunctorOps[F,A]
[error]  are possible conversion functions from F[Option[A]] to ?{def map: ?}
[error]           e.toOption.run.map(_.toStream)
[error]                      ^
```

The workaround appears to be that I need to put my scalaz function in a separate file.

But wouldn't it be nice if there was a way of removing the cats imports in a local scope? Do you think that would be possible? Probably needs a compiler plugin.

**Comment by djspiewak** [comment]
Hmm. I don't think there's a deterministic way of actually *removing* things from the implicit scope, even with compiler internals.  I think the best way to do this is probably a) use the a la carte imports instead of the one-size-fits-all versions (this will also improve your compile times), and b) try to scope some of the imports a little more tightly.  Having `cats._` and `scalaz._, Scalaz._` and `shims._` imported all in the same file is conflicted *by definition*.

**Comment by fommil** [comment]
I've seen very little evidence that a la carte actually speeds up the compile... this only seems to matter for shapeless style generic derivations (which is fixed in `scalaz-deriving`)

**Comment by djspiewak** [comment]
@fommil A test was done quite a while ago by Bill Venners. His results were extremely compelling, but that was also against like, Scala 2.9 or something.

If nothing else, a la carte imports are considerably more declarative. Aside from the `Applicative`/`Traverse` scenario, I have yet to find a situation where they *aren't* more maintainable long-term on complex codebases.
