### ISSUE TITLE
support for EitherT

### ISSUE THREAD

**Issue by fommil** [djspiewak/shims#14]
it seems there is no `asCats` or `asScalaz` convertor for `EitherT`?

**Comment by fommil** [comment]
I don't know the idiomatic way to do this, but the following seems to suffice as a workaround

```scala
  implicit class CatsToScalaz[F[_], A, B](e: cats.data.EitherT[F, A, B]) {
    import cats.implicits._
    def asScalaz(implicit F: cats.Functor[F]): scalaz.EitherT[F, A, B] =
      scalaz.EitherT(e.value.map(_.asScalaz))
  }

  implicit class ScalazToCats[F[_], A, B](e: scalaz.EitherT[F, A, B]) {
    import scalaz.Scalaz._
    def asCats(implicit F: scalaz.Functor[F]): cats.data.EitherT[F, A, B] =
      cats.data.EitherT(e.run.map(_.asCats))
  }
```

**Comment by djspiewak** [comment]
Oh weird. I'm actually surprised I didn't implement this!  I'll take care of it in the next release.

For the record, it's going to look a bit like this:

```scala
trait EitherConverters {

  implicit def eitherAs[A, B] = new AsScalaz[Either[A, B], A \/ B] with AsCats[A \/ B, Either[A, B]] {
    def c2s(e: Either[A, B]) = \/.fromEither(e)
    def s2c(e: A \/ B) = e.fold(l => Left(l), r => Right(r))
  }
}
```

**Comment by fommil** [comment]
awesome, thanks!

**Comment by fommil** [comment]
oh, hold on, you've done Either, not EitherT... was Either also missing?

**Comment by djspiewak** [comment]
No, `Either` was always there. It was just `EitherT` that was missing.

**Comment by fommil** [comment]
"look a bit **like** this"

![](https://media.giphy.com/media/xT5LMzIK1AdZJ4cYW4/giphy.gif)
