### ISSUE TITLE
cats `show` interpolator doesn't work

### ISSUE THREAD

**Issue by edmundnoble** [djspiewak/shims#17]
Using a `scalaz.Show` instance with cats' `show` interpolator results in a type mismatch as a result of a failed implicit conversion `A => Shown`, presumably because of implicit chaining issues.

**Comment by djspiewak** [comment]
Oh that's definitely interesting! Should be possible to make this work nicer.

**Comment by djspiewak** [comment]
Actually the problem here is that `Show` isn't converted at all.

**Comment by djspiewak** [comment]
This is fixed in v1.2.1
