### ISSUE TITLE
Cats Effect Instances

### ISSUE THREAD

**Issue by ChristopherDavenport** [djspiewak/shims#19]
My understanding is this library works to establish a bridge between scalaz and cats. Cats-effect typeclasses are now being used in parametric coding for quite a few tools. 

[scalaz-task-effect](https://christopherdavenport.github.io/scalaz-task-effect/)  exports a valid `Effect` instance for `scalaz.concurrent.Task`, that I would like to make sure is available to help this bridge.

Would this library also like to house the cats-effect instances for things like `scalaz.concurrent.Task`, `scalaz.effect.IO` etc?

It may be that nothing more is required than the above library, as it sounds like the new IO will be exporting its own instances. Just making sure to reach out to optimize the effectiveness of available tools.

**Comment by djspiewak** [comment]
I've been thinking about this for a while, and I think the right approach is to have an `effect` subproject (in this repo) which exposes a `shims.effect` package. What we put *in* that package is sort of an open question.

Scalaz 8 isn't going to be supported by shims for a while, and my understanding is that the scalaz-effect typeclasses aren't going to be backported. So there's no direct need for backport conversions. Having an `Effect` for `Task` is really nice, but it's also something that is almost better provided by a separated library like yours.

What do you think?

**Comment by ChristopherDavenport** [comment]
I think that until scalaz-effect typeclasses take off then shims will hopefully step into that role. As far as `Task` it will likely work fine in my little library. As I don't expect the instances to change much except for keeping up with the upstream libraries. Community trust being critical and not splitting solutions unnecessarily when they possibly should be working together.

My apologies on the delay getting back to you, the github issue got away from me.

**Comment by djspiewak** [comment]
@ChristopherDavenport Agreed. Also it remains to be seen exactly what final form the various hierarchies are going to settle into.

Closing this for now. Feel free to reopen if you feel there are more points to address; I think we've reached a good consensus.
