### ISSUE TITLE
Add cats-effect instances

### ISSUE THREAD

**Issue by djspiewak** [djspiewak/shims#21]
So apparently we really do need to pull these in here. @christopherdavenport was right! The issue is that `cats.effect.Effect` extends `cats.Monad`, which in turn makes `shims.MonadConversions` ambiguous. So… that's annoying. And it's a *very* common use-case.

The only way to resolve this is to have a **shims-effect** subproject which re-cakes the `shims` package object, providing `Effect[Task]` and stuff like that. This ensures that the implicit priority is correct, which isn't something that can otherwise be done externally (since shims is brought in via an import).

**Comment by djspiewak** [comment]
@christopherdavenport Can I crib some of the work from your excellent scalaz-task-effect library? Normally, I'm a huge fan of smaller a la carte libraries, but in this case there's no other way to get the implicit scoping right.

**Comment by ChristopherDavenport** [comment]
@djspiewak Absolutely. Apache License is perfectly fine by me. I'd be very happy to extend all that work to be included here as appropriate.

I would like developer attribution on the new library, as once this work is completed my lib will likely wither into non-existence. 

I'd also offer to help maintain if you are interested, but understand that this is your work and extra voices/hands may not be needed.

**Comment by djspiewak** [comment]
Done in v1.3.0
