### ISSUE TITLE
MonadError conversion

### ISSUE THREAD

**Issue by danslapman** [djspiewak/shims#9]
Please, add MonadError typeclass conversion

**Comment by danslapman** [comment]
Are there any plans on this?

**Comment by djspiewak** [comment]
Definitely plans, but the problem right now is that I'm trying to find a way around the ambiguity between the directions of the conversions.  That has sort of stalled me out on other changes to shims.

**Comment by djspiewak** [comment]
Now that I've gotten around the ambiguity blocker, I'll get to work on adding new conversions.  `MonadError` is at the top of the list.
